listen=YES
listen_ipv6=NO
background=NO
anonymous_enable=YES
local_enable=NO
write_enable=NO
anon_world_readable_only=YES
no_anon_password=YES
anon_root=/srv/ftp
hide_ids=YES
pasv_enable=YES
pasv_min_port=21200
pasv_max_port=21209
pasv_address=__PASV_ADDRESS__
connect_from_port_20=YES
use_localtime=YES
xferlog_enable=YES
log_ftp_protocol=YES
seccomp_sandbox=NO
