#!/usr/bin/env python3
"""Generate Linkora's Material Symbols font subsets and ArkTS registry."""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

try:
    from fontTools import subset
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
except ImportError as error:
    raise SystemExit(
        "fontTools is required. Install it with: python -m pip install fonttools"
    ) from error


OUTLINED_FAMILY = "Linkora Material Symbols Outlined"
FILLED_FAMILY = "Linkora Material Symbols Filled"


def download(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": "Linkora icon generator"})
    with urllib.request.urlopen(request) as response:
        return response.read()


def parse_codepoints(raw: bytes) -> dict[str, int]:
    result: dict[str, int] = {}
    for line in raw.decode("utf-8").splitlines():
        if not line.strip():
            continue
        name, codepoint = line.split()
        result[name] = int(codepoint, 16)
    return result


def validate_icons(icons: list[dict[str, Any]], codepoints: dict[str, int]) -> None:
    enum_names = [icon["enum"] for icon in icons]
    values = [icon["value"] for icon in icons]
    if len(enum_names) != len(set(enum_names)):
        raise ValueError("Duplicate enum name in icons.json")
    if len(values) != len(set(values)):
        raise ValueError("Duplicate enum value in icons.json")
    missing = sorted({icon["name"] for icon in icons if icon["name"] not in codepoints})
    if missing:
        raise ValueError(f"Unknown Material Symbols names: {', '.join(missing)}")
    invalid_fill = sorted({icon.get("fill", 0) for icon in icons} - {0, 1})
    if invalid_fill:
        raise ValueError(f"Only FILL 0 and 1 are supported: {invalid_fill}")


def set_font_names(font: TTFont, family: str) -> None:
    names = font["name"]
    postscript_name = family.replace(" ", "")
    for name_id, value in ((1, family), (2, "Regular"), (4, family), (6, postscript_name)):
        names.setName(value, name_id, 3, 1, 0x409)
        names.setName(value, name_id, 1, 0, 0)


def build_subset(
    font_bytes: bytes,
    codepoints: set[int],
    axes: dict[str, int],
    family: str,
    output: Path,
) -> int:
    font = TTFont(io.BytesIO(font_bytes), recalcBBoxes=False, recalcTimestamp=False)
    instantiateVariableFont(font, axes, inplace=True, optimize=True)

    options = subset.Options()
    options.layout_features = []
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6]
    options.name_legacy = True
    options.name_languages = [0x409]
    options.recalc_timestamp = False
    subsetter = subset.Subsetter(options=options)
    subsetter.populate(unicodes=codepoints)
    subsetter.subset(font)
    set_font_names(font, family)

    output.parent.mkdir(parents=True, exist_ok=True)
    font.save(output, reorderTables=True)
    return output.stat().st_size


def arkts_registry(icons: list[dict[str, Any]], codepoints: dict[str, int]) -> str:
    enum_lines = [f"  {icon['enum']} = '{icon['value']}'," for icon in icons]
    enum_lines[-1] = enum_lines[-1].rstrip(",")

    glyph_cases = [
        f"    case AppIconName.{icon['enum']}:\n"
        f"      return '\\u{codepoints[icon['name']]:04X}';"
        for icon in icons
    ]
    filled_icons = [icon for icon in icons if icon.get("fill", 0) == 1]
    filled_cases = [
        f"    case AppIconName.{icon['enum']}:" for icon in filled_icons
    ]

    return "\n".join(
        [
            "// Generated by scripts/update-material-icons.ps1. Do not edit manually.",
            "",
            f"export const APP_ICON_FONT_OUTLINED: string = '{OUTLINED_FAMILY}';",
            f"export const APP_ICON_FONT_FILLED: string = '{FILLED_FAMILY}';",
            "",
            "export enum AppIconName {",
            *enum_lines,
            "}",
            "",
            "export function appIconGlyph(name: AppIconName): string {",
            "  switch (name) {",
            *glyph_cases,
            "    default:",
            "      return '\\uE8B6';",
            "  }",
            "}",
            "",
            "export function appIconUsesFilledFont(name: AppIconName): boolean {",
            "  switch (name) {",
            *filled_cases,
            "      return true;",
            "    default:",
            "      return false;",
            "  }",
            "}",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--project-root", type=Path, required=True)
    args = parser.parse_args()

    project_root = args.project_root.resolve()
    manifest_path = project_root / "scripts" / "material-icons" / "icons.json"
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    source = manifest["source"]
    icons = manifest["icons"]

    print("Downloading the official Material Symbols source...")
    font_bytes = download(source["fontUrl"])
    codepoint_bytes = download(source["codepointsUrl"])
    codepoints = parse_codepoints(codepoint_bytes)
    validate_icons(icons, codepoints)

    axes_base = {
        "wght": source["weight"],
        "GRAD": source["grade"],
        "opsz": source["opticalSize"],
    }
    font_dir = project_root / "entry" / "src" / "main" / "resources" / "rawfile" / "font"
    outputs = []
    for fill, family, filename in (
        (0, OUTLINED_FAMILY, "linkora_material_symbols_outlined.ttf"),
        (1, FILLED_FAMILY, "linkora_material_symbols_filled.ttf"),
    ):
        selected = {codepoints[icon["name"]] for icon in icons if icon.get("fill", 0) == fill}
        axes = dict(axes_base, FILL=fill)
        output = font_dir / filename
        size = build_subset(font_bytes, selected, axes, family, output)
        outputs.append({"file": str(output.relative_to(project_root)), "bytes": size, "fill": fill})
        print(f"Generated {output.relative_to(project_root)} ({size} bytes, {len(selected)} glyphs)")

    registry_path = (
        project_root
        / "entry"
        / "src"
        / "main"
        / "ets"
        / "components"
        / "generated"
        / "MaterialIconRegistry.ets"
    )
    registry_path.write_text(arkts_registry(icons, codepoints), encoding="utf-8", newline="\n")

    lock = {
        "source": source,
        "sourceFontSha256": hashlib.sha256(font_bytes).hexdigest(),
        "sourceCodepointsSha256": hashlib.sha256(codepoint_bytes).hexdigest(),
        "iconCount": len(icons),
        "outputs": outputs,
    }
    lock_path = project_root / "scripts" / "material-icons" / "material-icons.lock.json"
    lock_path.write_text(json.dumps(lock, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Generated {registry_path.relative_to(project_root)}")
    print(f"Recorded source hashes in {lock_path.relative_to(project_root)}")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as error:
        print(f"Material icon generation failed: {error}", file=sys.stderr)
        sys.exit(1)
