cmake_minimum_required(VERSION 3.5.0)
project(linkora_smb)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_LIBDCERPC OFF CACHE BOOL "" FORCE)
set(ENABLE_LIBKRB5 OFF CACHE BOOL "" FORCE)
set(ENABLE_GSSAPI OFF CACHE BOOL "" FORCE)

add_subdirectory(third_party/libsmb2)

set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTS OFF CACHE BOOL "" FORCE)
set(ENABLE_DOCUMENTATION OFF CACHE BOOL "" FORCE)
set(ENABLE_UTILS OFF CACHE BOOL "" FORCE)
set(ENABLE_EXAMPLES OFF CACHE BOOL "" FORCE)
set(ENABLE_MULTITHREADING OFF CACHE BOOL "" FORCE)
set(ENABLE_NFS4_2 OFF CACHE BOOL "" FORCE)
set(ENABLE_TLS OFF CACHE STRING "" FORCE)
add_subdirectory(third_party/libnfs)

set(ENABLE_PROGRAMS OFF CACHE BOOL "" FORCE)
set(ENABLE_TESTING OFF CACHE BOOL "" FORCE)
set(MBEDTLS_FATAL_WARNINGS OFF CACHE BOOL "" FORCE)
set(USE_STATIC_MBEDTLS_LIBRARY ON CACHE BOOL "" FORCE)
set(USE_SHARED_MBEDTLS_LIBRARY OFF CACHE BOOL "" FORCE)
add_subdirectory(third_party/mbedtls)

set(BUILD_STATIC_LIBS ON CACHE BOOL "" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_TESTING OFF CACHE BOOL "" FORCE)
set(CRYPTO_BACKEND "mbedTLS" CACHE STRING "" FORCE)
set(LINKORA_SKIP_LIBSSH2_EXPORT TRUE)
set(MBEDTLS_FOUND TRUE)
set(MBEDTLS_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/third_party/mbedtls/include" CACHE PATH "" FORCE)
set(MBEDCRYPTO_LIBRARY "mbedcrypto" CACHE FILEPATH "" FORCE)
set(MBEDTLS_INCLUDE_DIRS "${CMAKE_CURRENT_SOURCE_DIR}/third_party/mbedtls/include")
set(MBEDTLS_LIBRARIES mbedcrypto)
add_subdirectory(third_party/libssh2)

add_library(linkora_smb SHARED napi_init.cpp)
target_compile_features(linkora_smb PRIVATE cxx_std_17)
target_link_libraries(linkora_smb PRIVATE smb2 libace_napi.z.so)
target_include_directories(linkora_smb PRIVATE third_party/libsmb2/include)

add_library(linkora_ftp SHARED ftp_init.cpp)
target_compile_features(linkora_ftp PRIVATE cxx_std_17)
target_link_libraries(linkora_ftp PRIVATE libace_napi.z.so)

add_library(linkora_sftp SHARED sftp_init.cpp)
target_compile_features(linkora_sftp PRIVATE cxx_std_17)
target_link_libraries(linkora_sftp PRIVATE libssh2_static mbedcrypto libace_napi.z.so)
target_include_directories(linkora_sftp PRIVATE third_party/libssh2/include)

add_library(linkora_nfs SHARED nfs_init.cpp)
target_compile_features(linkora_nfs PRIVATE cxx_std_17)
target_link_libraries(linkora_nfs PRIVATE nfs libace_napi.z.so)
target_include_directories(linkora_nfs PRIVATE third_party/libnfs/include)
